package il.ac.hit.cyberrushhour;

import java.util.ArrayList;

import il.ac.hit.cyberrushhour.gameobjects.Car;

public class LevelsFactory {

    ArrayList<Car> easy;
    ArrayList<Car> medium;
    ArrayList<Car> hard;

    public ArrayList<Car> CallForEasy(){
        easy = new ArrayList<>();
        Car car = new Car();
        car.setGridX(1);
        car.setGridY(2);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(0);
        easy.add(car);
        car = new Car();
        car.setGridX(0);
        car.setGridY(0);
        car.setWidth(1);
        car.setHeight(3);
        car.setType(4);
        easy.add(car);
        car = new Car();
        car.setGridX(0);
        car.setGridY(3);
        car.setWidth(1);
        car.setHeight(2);
        car.setType(2);
        easy.add(car);
        car = new Car();
        car.setGridX(1);
        car.setGridY(0);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(1);
        easy.add(car);
        car = new Car();
        car.setGridX(1);
        car.setGridY(4);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(1);
        easy.add(car);
        car = new Car();
        car.setGridX(3);
        car.setGridY(1);
        car.setWidth(1);
        car.setHeight(3);
        car.setType(4);
        easy.add(car);
        car = new Car();
        car.setGridX(2);
        car.setGridY(5);
        car.setWidth(3);
        car.setHeight(1);
        car.setType(3);
        easy.add(car);
        car = new Car();
        car.setGridX(5);
        car.setGridY(3);
        car.setWidth(1);
        car.setHeight(3);
        car.setType(4);
        easy.add(car);
        return easy;
    }

    public ArrayList<Car> CallForMedium(){
        medium = new ArrayList<>();
        Car car = new Car();
        car.setGridX(1);
        car.setGridY(2);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(0);
        medium.add(car);
        car = new Car();
        car.setGridX(0);
        car.setGridY(0);
        car.setWidth(1);
        car.setHeight(3);
        car.setType(4);
        medium.add(car);
        car = new Car();
        car.setGridX(1);
        car.setGridY(0);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(1);
        medium.add(car);
        car = new Car();
        car.setGridX(3);
        car.setGridY(0);
        car.setWidth(1);
        car.setHeight(3);
        car.setType(4);
        medium.add(car);
        car = new Car();
        car.setGridX(2);
        car.setGridY(3);
        car.setWidth(1);
        car.setHeight(2);
        car.setType(2);
        medium.add(car);
        car = new Car();
        car.setGridX(3);
        car.setGridY(3);
        car.setWidth(3);
        car.setHeight(1);
        car.setType(3);
        medium.add(car);
        car = new Car();
        car.setGridX(2);
        car.setGridY(5);
        car.setWidth(3);
        car.setHeight(1);
        car.setType(3);
        medium.add(car);
        car = new Car();
        car.setGridX(5);
        car.setGridY(4);
        car.setWidth(1);
        car.setHeight(2);
        car.setType(2);
        medium.add(car);

        return medium;
    }

    public ArrayList<Car> CallForHard(){
        hard = new ArrayList<>();
        Car car = new Car();
        car.setGridX(1);
        car.setGridY(2);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(0);
        hard.add(car);
        car = new Car();
        car.setGridX(0);
        car.setGridY(0);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(1);
        hard.add(car);
        car = new Car();
        car.setGridX(0);
        car.setGridY(2);
        car.setWidth(1);
        car.setHeight(2);
        car.setType(2);
        hard.add(car);
        car = new Car();
        car.setGridX(0);
        car.setGridY(4);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(1);
        hard.add(car);
        car = new Car();
        car.setGridX(2);
        car.setGridY(3);
        car.setWidth(1);
        car.setHeight(3);
        car.setType(4);
        hard.add(car);
        car = new Car();
        car.setGridX(3);
        car.setGridY(1);
        car.setWidth(1);
        car.setHeight(2);
        car.setType(2);
        hard.add(car);
        car = new Car();
        car.setGridX(3);
        car.setGridY(0);
        car.setWidth(3);
        car.setHeight(1);
        car.setType(3);
        hard.add(car);
        car = new Car();
        car.setGridX(4);
        car.setGridY(1);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(1);
        hard.add(car);
        car = new Car();
        car.setGridX(3);
        car.setGridY(3);
        car.setWidth(2);
        car.setHeight(1);
        car.setType(1);
        hard.add(car);
        car = new Car();
        car.setGridX(3);
        car.setGridY(5);
        car.setWidth(3);
        car.setHeight(1);
        car.setType(3);
        hard.add(car);
        car = new Car();
        car.setGridX(5);
        car.setGridY(2);
        car.setWidth(1);
        car.setHeight(3);
        car.setType(4);
        hard.add(car);

        return hard;
    }

}
